### ISSUE TITLE
Bad permission to yorc.pem certificate while deploying yorc server based on TOSCA component

### ISSUE THREAD

**Issue by gavillom** [ystia/forge#17]
Hi,

I was able to deploy a yorc server from TOSCA component (through a4c_yorc_basic topology).
I've defined the yorc "keypair" property.

If I try to launch a deployment from the installed yorc, I got the following error : 

[2018-10-02T08:24:27.743593265Z][ERROR][elk-demo-Environment][install][7f8c9e23-8ef7-4390-9b43-de9a0f1d2a37][Consul_Server][0][standard][create][]Giving up retries for Ansible error: 'exit status 4' (5/5)

Trying to connect to the server manually, I got the following  error : 
sudo -u yorc ssh -i /var/yorc/.ssh/yorc.pem root@10.0.0.114
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@         WARNING: UNPROTECTED PRIVATE KEY FILE!          @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0644 for '/var/yorc/.ssh/yorc.pem' are too open.
It is required that your private key files are NOT accessible by others.
This private key will be ignored.
Load key "/var/yorc/.ssh/yorc.pem": bad permissions
Permission denied (publickey,gssapi-keyex,gssapi-with-mic).

It feels like permission is not correctly set. Should be 600 while it's 644.

Mathis

**Comment by loicalbertin** [comment]
You are right this one could be easily fixed but to me this part is not modeled properly. This property should not be specified on the Openstack config but on Yorc directly as it is used on several infrastructure

**Comment by gavillom** [comment]
Last commit resolve the issue. Good to me.
