### ISSUE TITLE
Kubernetes master failed to install - OpenStack

### ISSUE THREAD

**Issue by Loic-R** [ystia/forge#47]
On Openstack infra, topology K8S cluster failed to be deploy cause workflow install of kubemaster component failed. Here is the error trace on alien4cloud

```
[2018-12-20 12:42:54] [install] [KubernetesMaster] Ansible task output:
PLAY [Install Kubeadm, Kubelet & Kubectl] TASK [Set net cidr fact]
fatal: [10.197.138.53]: FAILED! => 
msg: The ipaddr filter requires python-netaddr be installed on the ansible controller
[2018-12-20 12:42:54] [install] [KubernetesMaster] Ansible execution for operation "standard.create" on node "KubernetesMaster" failed
```

**Comment by Loic-R** [comment]
In fact I didn't see that there were python packages requirement to be installed on yorc host...

https://github.com/ystia/forge/blob/develop/org/ystia/kubernetes/linux/ansible/playbooks/requirements.txt

Is there a better solution or we mark this issue closed supposing users have to install this python packages ? @loicalbertin @laurentganne @adidanes What do you think ?

**Comment by loicalbertin** [comment]
I think we can just close this one.
